name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp: ['23.2','23.1','23.0','22.3']
        elixir: ['1.11.3', '1.11.2']

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --unshallow --tags
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --trace
    - name: Debug via SSH
      uses: luchihoratiu/debug-via-ssh@v1.0
